trigger:
  batch: true
  branches:
    include:
    - master
    - release/*
  paths:
    exclude:
    - docs/*
    
pr:
  branches:
    include:
    - master
    - release/*
  paths:
    exclude:
    - docs/*
    
variables:
- template: common-variables.yml

stages:
- stage: build
  displayName: Build
  jobs:
  - template: /eng/common/templates/jobs/jobs.yml
    parameters:
      artifacts:
        publish:
          artifacts: true
          logs: true
          manifests: true
      enableMicrobuild: true
      enablePublishUsingPipelines: true
      workspace:
        clean: all
      jobs:
      - job: Windows_NT
        timeoutInMinutes: 90
        pool:
          ${{ if eq(variables._RunAsPublic, True) }}:
            vmimage: 'windows-latest'
          ${{ if eq(variables._RunAsInternal, True) }}:
            name: NetCoreInternal-Pool
            queue: BuildPool.Windows.10.Amd64.VS2019
        strategy:
          matrix:
            Build_Release:
              _BuildConfig: Release
            ${{ if eq(variables._RunAsPublic, True) }}:
              Build_Debug:
                _BuildConfig: Debug
        preSteps:
        - checkout: self
          clean: true
        steps:
        - script: eng\common\cibuild.cmd
            -configuration $(_BuildConfig) 
            -prepareMachine
          displayName: Windows Build / Publish
      - ${{ if eq(variables._RunAsPublic, True) }}:
        - job: Linux
          pool:
            vimage: 'ubuntu-latest'
          strategy:
            matrix:
              Build_Debug:
                _BuildConfig: Debug
              Build_Release:
                _BuildConfig: Release
          preSteps:
          - checkout: self
            clean: true
          steps:
          - script: eng/common/cibuild.sh
              --configuration $(_BuildConfig)
              --prepareMachine
            displayName: Linux Build / Publish

- ${{ if eq(variables._RunAsInternal, True) }}:
  - template: /eng/common/templates/post-build/post-build.yml
    parameters:
      enableSourceLinkValidation: false